### ISSUE TITLE
Issue creating bin directory in electron asar package

### ISSUE THREAD

**Issue by agmcleod** [vot/ffbinaries-node#1]
Hi there. I ran into an issue where the package tries to create the bin folder: https://github.com/vot/ffbinaries-node/blob/master/ffbinaries-lib.js#L25, so it can ensure there is a destination to use here: https://github.com/vot/ffbinaries-node/blob/master/ffbinaries-lib.js#L303. Since I am using an asar package, it's not able to create a directory within the package itself. So i get a ENOTDIR error.

In my case i am specifying a destination to `ffbinaries.downloadFiles`, so I'm wondering if creating the bin directory should be invoked at function call time, instead of initialization time.

Anyways thanks for this package, it's been awesome for a small audio tool i've been wanting to make.

**Comment by vot** [comment]
Hey there agmcleod,

I meant to remove the `LOCAL_BIN` altogether as it's not really necessary anyway (it'll fallback to `path.resolve('.')`). Feel free to send over a pull request for this, otherwise I'll do that tomorrow and publish the updated package to npm shortly afterwards.

Thanks for using the package, I created it so that I can use it in a similar scenario to what you're describing but just didn't get around to using it properly yet. I'm glad you find it useful :)

**Comment by vot** [comment]
I just merged your pull request and I published version 0.1.4 to npm.

Cheers!

**Comment by agmcleod** [comment]
@vot awesome, glad i could lend a quick hand :)
