### ISSUE TITLE
Download progress

### ISSUE THREAD

**Issue by dudewheresmycode** [vot/ffbinaries-node#23]
Is it currently possible to provide a download progress callback in the `downloadFiles` method? Just want to make sure I didn't miss something in the docs, before I hack around on it.

**Comment by dudewheresmycode** [comment]
I noticed a `tickFn` in the source. So it looks like you had maybe started down this path. I got it working for my needs and submitted a PR (#24 )

**Comment by vot** [comment]
Hi @dudewheresmycode,

Cheers for looking into it - `tickerFn` is there precisely for this task; it is used in `cli.js` right now.

Good idea to just provide percentage, far more useful in this context.

In case someone integrates that in their app already - I'll release this as `1.1.0` rather than `1.0.10` to avoid issues with existing progress indicators.

I'll close this issue and merge a PR shortly (I suggested one update in `cli.js`).
